<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.t_Daten" Member="t_Datens">
    <Type Name="t_Daten">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Tracker" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(24,18) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(24,18) NOT NULL" CanBeNull="false" />
      <Column Name="Altitude" Type="System.Decimal" DbType="Decimal(24,18) NOT NULL" CanBeNull="false" />
      <Column Name="Speed" Type="System.Decimal" DbType="Decimal(24,18) NOT NULL" CanBeNull="false" />
      <Column Name="Penalty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Polygon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_Tracker_t_Daten" Member="t_Tracker" ThisKey="ID_Tracker" OtherKey="ID" Type="t_Tracker" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Tracker" Member="t_Trackers">
    <Type Name="t_Tracker">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IMEI" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="t_Tracker_t_Daten" Member="t_Datens" ThisKey="ID" OtherKey="ID_Tracker" Type="t_Daten" />
    </Type>
  </Table>
  <Table Name="dbo.t_GPS_IN" Member="t_GPS_INs">
    <Type Name="t_GPS_IN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IMEI" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GPS_fix" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimestampTracker" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="longitude" Type="System.String" DbType="NChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.String" DbType="NChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="altitude" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="speed" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="heading" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="nr_used_sat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HDOP" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Processed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.t_Log" Member="t_Logs">
    <Type Name="t_Log">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="project" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.t_Picture" Member="t_Pictures">
    <Type Name="t_Picture">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.t_Pilot" Member="t_Pilots">
    <Type Name="t_Pilot">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SureName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ID_Tracker" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Picture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ID_Flag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="t_Pilot_t_Race" Member="t_Races" ThisKey="ID" OtherKey="ID_Pilot_0" Type="t_Race" />
      <Association Name="t_Pilot_t_Race1" Member="t_Races1" ThisKey="ID" OtherKey="ID_Pilot_1" Type="t_Race" />
      <Association Name="t_Pilot_t_Race2" Member="t_Races2" ThisKey="ID" OtherKey="ID_Pilot_2" Type="t_Race" />
      <Association Name="t_Pilot_t_Race3" Member="t_Races3" ThisKey="ID" OtherKey="ID_Pilot_3" Type="t_Race" />
    </Type>
  </Table>
  <Table Name="dbo.t_Polygon" Member="t_Polygons">
    <Type Name="t_Polygon">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PolygonGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_Polygon_t_PolygonPoint" Member="t_PolygonPoints" ThisKey="ID" OtherKey="ID_Polygon" Type="t_PolygonPoint" />
      <Association Name="t_PolygonGroup_t_Polygon" Member="t_PolygonGroup" ThisKey="ID_PolygonGroup" OtherKey="ID" Type="t_PolygonGroup" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_PolygonGroup" Member="t_PolygonGroups">
    <Type Name="t_PolygonGroup">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="t_PolygonGroup_t_Polygon" Member="t_Polygons" ThisKey="ID" OtherKey="ID_PolygonGroup" Type="t_Polygon" />
      <Association Name="t_PolygonGroup_t_Race" Member="t_Races" ThisKey="ID" OtherKey="ID_PolygonGroup" Type="t_Race" />
    </Type>
  </Table>
  <Table Name="dbo.t_PolygonPoints" Member="t_PolygonPoints">
    <Type Name="t_PolygonPoint">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="longitude" Type="System.Decimal" DbType="Decimal(24,14) NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.Decimal" DbType="Decimal(24,14) NOT NULL" CanBeNull="false" />
      <Column Name="altitude" Type="System.Decimal" DbType="Decimal(24,14) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Polygon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_Polygon_t_PolygonPoint" Member="t_Polygon" ThisKey="ID_Polygon" OtherKey="ID" Type="t_Polygon" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Race" Member="t_Races">
    <Type Name="t_Race">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ID_Pilot_0" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Pilot_1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Pilot_2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Pilot_3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_PolygonGroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="t_Pilot_t_Race" Member="t_Pilot" ThisKey="ID_Pilot_0" OtherKey="ID" Type="t_Pilot" IsForeignKey="true" />
      <Association Name="t_Pilot_t_Race1" Member="t_Pilot1" ThisKey="ID_Pilot_1" OtherKey="ID" Type="t_Pilot" IsForeignKey="true" />
      <Association Name="t_Pilot_t_Race2" Member="t_Pilot2" ThisKey="ID_Pilot_2" OtherKey="ID" Type="t_Pilot" IsForeignKey="true" />
      <Association Name="t_Pilot_t_Race3" Member="t_Pilot3" ThisKey="ID_Pilot_3" OtherKey="ID" Type="t_Pilot" IsForeignKey="true" />
      <Association Name="t_PolygonGroup_t_Race" Member="t_PolygonGroup" ThisKey="ID_PolygonGroup" OtherKey="ID" Type="t_PolygonGroup" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>