//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("DatabaseModel", "FK_t_Daten_t_Flugzeug", "t_Flugzeug", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataService.t_Flugzeug), "t_Daten", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.t_Daten))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("DatabaseModel", "FK_t_Flugzeug_t_Tracker", "t_Tracker", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataService.t_Tracker), "t_Flugzeug", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.t_Flugzeug))]

// Original file name:
// Generation date: 11.05.2009 11:50:33
namespace DataService
{
    
    /// <summary>
    /// There are no comments for DatabaseEntities in the schema.
    /// </summary>
    public partial class DatabaseEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : 
                base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : 
                base(connectionString, "DatabaseEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "DatabaseEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for t_Daten in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<t_Daten> t_Daten
        {
            get
            {
                if ((this._t_Daten == null))
                {
                    this._t_Daten = base.CreateQuery<t_Daten>("[t_Daten]");
                }
                return this._t_Daten;
            }
        }
        private global::System.Data.Objects.ObjectQuery<t_Daten> _t_Daten;
        /// <summary>
        /// There are no comments for t_Flugzeug in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<t_Flugzeug> t_Flugzeug
        {
            get
            {
                if ((this._t_Flugzeug == null))
                {
                    this._t_Flugzeug = base.CreateQuery<t_Flugzeug>("[t_Flugzeug]");
                }
                return this._t_Flugzeug;
            }
        }
        private global::System.Data.Objects.ObjectQuery<t_Flugzeug> _t_Flugzeug;
        /// <summary>
        /// There are no comments for t_GPS_IN in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<t_GPS_IN> t_GPS_IN
        {
            get
            {
                if ((this._t_GPS_IN == null))
                {
                    this._t_GPS_IN = base.CreateQuery<t_GPS_IN>("[t_GPS_IN]");
                }
                return this._t_GPS_IN;
            }
        }
        private global::System.Data.Objects.ObjectQuery<t_GPS_IN> _t_GPS_IN;
        /// <summary>
        /// There are no comments for t_Tracker in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<t_Tracker> t_Tracker
        {
            get
            {
                if ((this._t_Tracker == null))
                {
                    this._t_Tracker = base.CreateQuery<t_Tracker>("[t_Tracker]");
                }
                return this._t_Tracker;
            }
        }
        private global::System.Data.Objects.ObjectQuery<t_Tracker> _t_Tracker;
        /// <summary>
        /// There are no comments for t_Daten in the schema.
        /// </summary>
        public void AddTot_Daten(t_Daten t_Daten)
        {
            base.AddObject("t_Daten", t_Daten);
        }
        /// <summary>
        /// There are no comments for t_Flugzeug in the schema.
        /// </summary>
        public void AddTot_Flugzeug(t_Flugzeug t_Flugzeug)
        {
            base.AddObject("t_Flugzeug", t_Flugzeug);
        }
        /// <summary>
        /// There are no comments for t_GPS_IN in the schema.
        /// </summary>
        public void AddTot_GPS_IN(t_GPS_IN t_GPS_IN)
        {
            base.AddObject("t_GPS_IN", t_GPS_IN);
        }
        /// <summary>
        /// There are no comments for t_Tracker in the schema.
        /// </summary>
        public void AddTot_Tracker(t_Tracker t_Tracker)
        {
            base.AddObject("t_Tracker", t_Tracker);
        }
    }
    /// <summary>
    /// There are no comments for DatabaseModel.t_Daten in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="t_Daten")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class t_Daten : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new t_Daten object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        public static t_Daten Createt_Daten(int id, global::System.DateTime timestamp)
        {
            t_Daten t_Daten = new t_Daten();
            t_Daten.ID = id;
            t_Daten.Timestamp = timestamp;
            return t_Daten;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this.ReportPropertyChanging("Timestamp");
                this._Timestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Timestamp");
                this.OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();
        /// <summary>
        /// There are no comments for Property XStart in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> XStart
        {
            get
            {
                return this._XStart;
            }
            set
            {
                this.OnXStartChanging(value);
                this.ReportPropertyChanging("XStart");
                this._XStart = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("XStart");
                this.OnXStartChanged();
            }
        }
        private global::System.Nullable<decimal> _XStart;
        partial void OnXStartChanging(global::System.Nullable<decimal> value);
        partial void OnXStartChanged();
        /// <summary>
        /// There are no comments for Property XEnd in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> XEnd
        {
            get
            {
                return this._XEnd;
            }
            set
            {
                this.OnXEndChanging(value);
                this.ReportPropertyChanging("XEnd");
                this._XEnd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("XEnd");
                this.OnXEndChanged();
            }
        }
        private global::System.Nullable<decimal> _XEnd;
        partial void OnXEndChanging(global::System.Nullable<decimal> value);
        partial void OnXEndChanged();
        /// <summary>
        /// There are no comments for Property YStart in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> YStart
        {
            get
            {
                return this._YStart;
            }
            set
            {
                this.OnYStartChanging(value);
                this.ReportPropertyChanging("YStart");
                this._YStart = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("YStart");
                this.OnYStartChanged();
            }
        }
        private global::System.Nullable<decimal> _YStart;
        partial void OnYStartChanging(global::System.Nullable<decimal> value);
        partial void OnYStartChanged();
        /// <summary>
        /// There are no comments for Property YEnd in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> YEnd
        {
            get
            {
                return this._YEnd;
            }
            set
            {
                this.OnYEndChanging(value);
                this.ReportPropertyChanging("YEnd");
                this._YEnd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("YEnd");
                this.OnYEndChanged();
            }
        }
        private global::System.Nullable<decimal> _YEnd;
        partial void OnYEndChanging(global::System.Nullable<decimal> value);
        partial void OnYEndChanged();
        /// <summary>
        /// There are no comments for Property ZStart in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> ZStart
        {
            get
            {
                return this._ZStart;
            }
            set
            {
                this.OnZStartChanging(value);
                this.ReportPropertyChanging("ZStart");
                this._ZStart = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ZStart");
                this.OnZStartChanged();
            }
        }
        private global::System.Nullable<decimal> _ZStart;
        partial void OnZStartChanging(global::System.Nullable<decimal> value);
        partial void OnZStartChanged();
        /// <summary>
        /// There are no comments for Property ZEnd in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> ZEnd
        {
            get
            {
                return this._ZEnd;
            }
            set
            {
                this.OnZEndChanging(value);
                this.ReportPropertyChanging("ZEnd");
                this._ZEnd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ZEnd");
                this.OnZEndChanged();
            }
        }
        private global::System.Nullable<decimal> _ZEnd;
        partial void OnZEndChanging(global::System.Nullable<decimal> value);
        partial void OnZEndChanged();
        /// <summary>
        /// There are no comments for Property TStart in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> TStart
        {
            get
            {
                return this._TStart;
            }
            set
            {
                this.OnTStartChanging(value);
                this.ReportPropertyChanging("TStart");
                this._TStart = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TStart");
                this.OnTStartChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _TStart;
        partial void OnTStartChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnTStartChanged();
        /// <summary>
        /// There are no comments for Property TEnd in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> TEnd
        {
            get
            {
                return this._TEnd;
            }
            set
            {
                this.OnTEndChanging(value);
                this.ReportPropertyChanging("TEnd");
                this._TEnd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TEnd");
                this.OnTEndChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _TEnd;
        partial void OnTEndChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnTEndChanged();
        /// <summary>
        /// There are no comments for Property Speed in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Speed
        {
            get
            {
                return this._Speed;
            }
            set
            {
                this.OnSpeedChanging(value);
                this.ReportPropertyChanging("Speed");
                this._Speed = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Speed");
                this.OnSpeedChanged();
            }
        }
        private string _Speed;
        partial void OnSpeedChanging(string value);
        partial void OnSpeedChanged();
        /// <summary>
        /// There are no comments for Property Penalty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Penalty
        {
            get
            {
                return this._Penalty;
            }
            set
            {
                this.OnPenaltyChanging(value);
                this.ReportPropertyChanging("Penalty");
                this._Penalty = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Penalty");
                this.OnPenaltyChanged();
            }
        }
        private global::System.Nullable<int> _Penalty;
        partial void OnPenaltyChanging(global::System.Nullable<int> value);
        partial void OnPenaltyChanged();
        /// <summary>
        /// There are no comments for Property ID_Polygon in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ID_Polygon
        {
            get
            {
                return this._ID_Polygon;
            }
            set
            {
                this.OnID_PolygonChanging(value);
                this.ReportPropertyChanging("ID_Polygon");
                this._ID_Polygon = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID_Polygon");
                this.OnID_PolygonChanged();
            }
        }
        private global::System.Nullable<int> _ID_Polygon;
        partial void OnID_PolygonChanging(global::System.Nullable<int> value);
        partial void OnID_PolygonChanged();
        /// <summary>
        /// There are no comments for t_Flugzeug in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_t_Daten_t_Flugzeug", "t_Flugzeug")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public t_Flugzeug t_Flugzeug
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<t_Flugzeug>("DatabaseModel.FK_t_Daten_t_Flugzeug", "t_Flugzeug").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<t_Flugzeug>("DatabaseModel.FK_t_Daten_t_Flugzeug", "t_Flugzeug").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for t_Flugzeug in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<t_Flugzeug> t_FlugzeugReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<t_Flugzeug>("DatabaseModel.FK_t_Daten_t_Flugzeug", "t_Flugzeug");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<t_Flugzeug>("DatabaseModel.FK_t_Daten_t_Flugzeug", "t_Flugzeug", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for DatabaseModel.t_Flugzeug in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="t_Flugzeug")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class t_Flugzeug : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new t_Flugzeug object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static t_Flugzeug Createt_Flugzeug(int id)
        {
            t_Flugzeug t_Flugzeug = new t_Flugzeug();
            t_Flugzeug.ID = id;
            return t_Flugzeug;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Flugzeug in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Flugzeug
        {
            get
            {
                return this._Flugzeug;
            }
            set
            {
                this.OnFlugzeugChanging(value);
                this.ReportPropertyChanging("Flugzeug");
                this._Flugzeug = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Flugzeug");
                this.OnFlugzeugChanged();
            }
        }
        private string _Flugzeug;
        partial void OnFlugzeugChanging(string value);
        partial void OnFlugzeugChanged();
        /// <summary>
        /// There are no comments for Property Pilot in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Pilot
        {
            get
            {
                return this._Pilot;
            }
            set
            {
                this.OnPilotChanging(value);
                this.ReportPropertyChanging("Pilot");
                this._Pilot = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Pilot");
                this.OnPilotChanged();
            }
        }
        private string _Pilot;
        partial void OnPilotChanging(string value);
        partial void OnPilotChanged();
        /// <summary>
        /// There are no comments for t_Daten in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_t_Daten_t_Flugzeug", "t_Daten")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<t_Daten> t_Daten
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<t_Daten>("DatabaseModel.FK_t_Daten_t_Flugzeug", "t_Daten");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<t_Daten>("DatabaseModel.FK_t_Daten_t_Flugzeug", "t_Daten", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for t_Tracker in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_t_Flugzeug_t_Tracker", "t_Tracker")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public t_Tracker t_Tracker
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<t_Tracker>("DatabaseModel.FK_t_Flugzeug_t_Tracker", "t_Tracker").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<t_Tracker>("DatabaseModel.FK_t_Flugzeug_t_Tracker", "t_Tracker").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for t_Tracker in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<t_Tracker> t_TrackerReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<t_Tracker>("DatabaseModel.FK_t_Flugzeug_t_Tracker", "t_Tracker");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<t_Tracker>("DatabaseModel.FK_t_Flugzeug_t_Tracker", "t_Tracker", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for DatabaseModel.t_GPS_IN in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="t_GPS_IN")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class t_GPS_IN : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new t_GPS_IN object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="iMEI">Initial value of IMEI.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="gPS_fix">Initial value of GPS_fix.</param>
        /// <param name="timestampTracker">Initial value of TimestampTracker.</param>
        /// <param name="longitude">Initial value of longitude.</param>
        /// <param name="latitude">Initial value of latitude.</param>
        /// <param name="altitude">Initial value of altitude.</param>
        /// <param name="speed">Initial value of speed.</param>
        /// <param name="heading">Initial value of heading.</param>
        /// <param name="nr_used_sat">Initial value of nr_used_sat.</param>
        /// <param name="hDOP">Initial value of HDOP.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        /// <param name="processed">Initial value of Processed.</param>
        public static t_GPS_IN Createt_GPS_IN(int id, string iMEI, int status, int gPS_fix, global::System.DateTime timestampTracker, string longitude, string latitude, string altitude, string speed, string heading, int nr_used_sat, string hDOP, global::System.DateTime timestamp, bool processed)
        {
            t_GPS_IN t_GPS_IN = new t_GPS_IN();
            t_GPS_IN.ID = id;
            t_GPS_IN.IMEI = iMEI;
            t_GPS_IN.Status = status;
            t_GPS_IN.GPS_fix = gPS_fix;
            t_GPS_IN.TimestampTracker = timestampTracker;
            t_GPS_IN.longitude = longitude;
            t_GPS_IN.latitude = latitude;
            t_GPS_IN.altitude = altitude;
            t_GPS_IN.speed = speed;
            t_GPS_IN.heading = heading;
            t_GPS_IN.nr_used_sat = nr_used_sat;
            t_GPS_IN.HDOP = hDOP;
            t_GPS_IN.Timestamp = timestamp;
            t_GPS_IN.Processed = processed;
            return t_GPS_IN;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property IMEI in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IMEI
        {
            get
            {
                return this._IMEI;
            }
            set
            {
                this.OnIMEIChanging(value);
                this.ReportPropertyChanging("IMEI");
                this._IMEI = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IMEI");
                this.OnIMEIChanged();
            }
        }
        private string _IMEI;
        partial void OnIMEIChanging(string value);
        partial void OnIMEIChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private int _Status;
        partial void OnStatusChanging(int value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property GPS_fix in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int GPS_fix
        {
            get
            {
                return this._GPS_fix;
            }
            set
            {
                this.OnGPS_fixChanging(value);
                this.ReportPropertyChanging("GPS_fix");
                this._GPS_fix = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GPS_fix");
                this.OnGPS_fixChanged();
            }
        }
        private int _GPS_fix;
        partial void OnGPS_fixChanging(int value);
        partial void OnGPS_fixChanged();
        /// <summary>
        /// There are no comments for Property TimestampTracker in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime TimestampTracker
        {
            get
            {
                return this._TimestampTracker;
            }
            set
            {
                this.OnTimestampTrackerChanging(value);
                this.ReportPropertyChanging("TimestampTracker");
                this._TimestampTracker = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TimestampTracker");
                this.OnTimestampTrackerChanged();
            }
        }
        private global::System.DateTime _TimestampTracker;
        partial void OnTimestampTrackerChanging(global::System.DateTime value);
        partial void OnTimestampTrackerChanged();
        /// <summary>
        /// There are no comments for Property longitude in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string longitude
        {
            get
            {
                return this._longitude;
            }
            set
            {
                this.OnlongitudeChanging(value);
                this.ReportPropertyChanging("longitude");
                this._longitude = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("longitude");
                this.OnlongitudeChanged();
            }
        }
        private string _longitude;
        partial void OnlongitudeChanging(string value);
        partial void OnlongitudeChanged();
        /// <summary>
        /// There are no comments for Property latitude in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string latitude
        {
            get
            {
                return this._latitude;
            }
            set
            {
                this.OnlatitudeChanging(value);
                this.ReportPropertyChanging("latitude");
                this._latitude = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("latitude");
                this.OnlatitudeChanged();
            }
        }
        private string _latitude;
        partial void OnlatitudeChanging(string value);
        partial void OnlatitudeChanged();
        /// <summary>
        /// There are no comments for Property altitude in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string altitude
        {
            get
            {
                return this._altitude;
            }
            set
            {
                this.OnaltitudeChanging(value);
                this.ReportPropertyChanging("altitude");
                this._altitude = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("altitude");
                this.OnaltitudeChanged();
            }
        }
        private string _altitude;
        partial void OnaltitudeChanging(string value);
        partial void OnaltitudeChanged();
        /// <summary>
        /// There are no comments for Property speed in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string speed
        {
            get
            {
                return this._speed;
            }
            set
            {
                this.OnspeedChanging(value);
                this.ReportPropertyChanging("speed");
                this._speed = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("speed");
                this.OnspeedChanged();
            }
        }
        private string _speed;
        partial void OnspeedChanging(string value);
        partial void OnspeedChanged();
        /// <summary>
        /// There are no comments for Property heading in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string heading
        {
            get
            {
                return this._heading;
            }
            set
            {
                this.OnheadingChanging(value);
                this.ReportPropertyChanging("heading");
                this._heading = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("heading");
                this.OnheadingChanged();
            }
        }
        private string _heading;
        partial void OnheadingChanging(string value);
        partial void OnheadingChanged();
        /// <summary>
        /// There are no comments for Property nr_used_sat in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int nr_used_sat
        {
            get
            {
                return this._nr_used_sat;
            }
            set
            {
                this.Onnr_used_satChanging(value);
                this.ReportPropertyChanging("nr_used_sat");
                this._nr_used_sat = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("nr_used_sat");
                this.Onnr_used_satChanged();
            }
        }
        private int _nr_used_sat;
        partial void Onnr_used_satChanging(int value);
        partial void Onnr_used_satChanged();
        /// <summary>
        /// There are no comments for Property HDOP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string HDOP
        {
            get
            {
                return this._HDOP;
            }
            set
            {
                this.OnHDOPChanging(value);
                this.ReportPropertyChanging("HDOP");
                this._HDOP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("HDOP");
                this.OnHDOPChanged();
            }
        }
        private string _HDOP;
        partial void OnHDOPChanging(string value);
        partial void OnHDOPChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this.ReportPropertyChanging("Timestamp");
                this._Timestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Timestamp");
                this.OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();
        /// <summary>
        /// There are no comments for Property Processed in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Processed
        {
            get
            {
                return this._Processed;
            }
            set
            {
                this.OnProcessedChanging(value);
                this.ReportPropertyChanging("Processed");
                this._Processed = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Processed");
                this.OnProcessedChanged();
            }
        }
        private bool _Processed;
        partial void OnProcessedChanging(bool value);
        partial void OnProcessedChanged();
    }
    /// <summary>
    /// There are no comments for DatabaseModel.t_Tracker in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="t_Tracker")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class t_Tracker : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new t_Tracker object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="iMEI">Initial value of IMEI.</param>
        public static t_Tracker Createt_Tracker(int id, string iMEI)
        {
            t_Tracker t_Tracker = new t_Tracker();
            t_Tracker.ID = id;
            t_Tracker.IMEI = iMEI;
            return t_Tracker;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property IMEI in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IMEI
        {
            get
            {
                return this._IMEI;
            }
            set
            {
                this.OnIMEIChanging(value);
                this.ReportPropertyChanging("IMEI");
                this._IMEI = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IMEI");
                this.OnIMEIChanged();
            }
        }
        private string _IMEI;
        partial void OnIMEIChanging(string value);
        partial void OnIMEIChanged();
        /// <summary>
        /// There are no comments for t_Flugzeug in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_t_Flugzeug_t_Tracker", "t_Flugzeug")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<t_Flugzeug> t_Flugzeug
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<t_Flugzeug>("DatabaseModel.FK_t_Flugzeug_t_Tracker", "t_Flugzeug");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<t_Flugzeug>("DatabaseModel.FK_t_Flugzeug_t_Tracker", "t_Flugzeug", value);
                }
            }
        }
    }
}
