//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationRaceLive
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnrlModel2Container : DbContext
    {
        public AnrlModel2Container()
            : base("name=AnrlModel2Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Competition> CompetitionSet { get; set; }
        public virtual DbSet<Map> MapSet { get; set; }
        public virtual DbSet<Picture> PictureSet { get; set; }
        public virtual DbSet<Subscriber> SubscriberSet { get; set; }
        public virtual DbSet<Team> TeamSet { get; set; }
        public virtual DbSet<QualificationRound> QualificationRoundSet { get; set; }
        public virtual DbSet<Line> LineSet { get; set; }
        public virtual DbSet<Parcour> ParcourSet { get; set; }
        public virtual DbSet<Flight> FlightSet { get; set; }
        public virtual DbSet<Penalty> PenaltySet { get; set; }
        public virtual DbSet<Point> PointSet { get; set; }
    }
}
