//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationRaceLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Competition
    {
        public t_Competition()
        {
            this.t_Competition_Team = new HashSet<t_Competition_Team>();
        }
    
        public int ID { get; set; }
        public long TimeTakeOff { get; set; }
        public long TimeStartLine { get; set; }
        public long TimeEndLine { get; set; }
        public int ID_TakeOffLine { get; set; }
        public string Name { get; set; }
        public int ID_Parcour { get; set; }
        public int ID_CompetitionSet { get; set; }
    
        public virtual ICollection<t_Competition_Team> t_Competition_Team { get; set; }
        public virtual t_CompetitionSet t_CompetitionSet { get; set; }
        public virtual t_Line TakeOffLine { get; set; }
    }
}
