//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationRaceLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Competition_Team
    {
        public t_Competition_Team()
        {
            this.t_Penalty = new HashSet<t_Penalty>();
            this.t_Tracker = new HashSet<t_Tracker>();
        }
    
        public int ID { get; set; }
        public int StartID { get; set; }
        public int Route { get; set; }
        public int ID_Team { get; set; }
        public int ID_Competition { get; set; }
        public long TimeTakeOff { get; set; }
        public long TimeStart { get; set; }
        public long TimeEnd { get; set; }
        public int ID_CompetitionSet { get; set; }
    
        public virtual t_Competition t_Competition { get; set; }
        public virtual ICollection<t_Penalty> t_Penalty { get; set; }
        public virtual t_Team t_Team { get; set; }
        public virtual ICollection<t_Tracker> t_Tracker { get; set; }
    }
}
