//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationRaceLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_GPSPoint
    {
        public t_GPSPoint()
        {
            this.edited = false;
            this.t_Line = new HashSet<t_Line>();
            this.t_Line1 = new HashSet<t_Line>();
            this.t_Line2 = new HashSet<t_Line>();
        }
    
        public int ID { get; set; }
        public double altitude { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
        public bool edited { get; set; }
        public long timestampGPS { get; set; }
        public double speed { get; set; }
        public double bearing { get; set; }
        public double accuracy { get; set; }
        public string identifier { get; set; }
        public long timestampSender { get; set; }
    
        public virtual ICollection<t_Line> t_Line { get; set; }
        public virtual ICollection<t_Line> t_Line1 { get; set; }
        public virtual ICollection<t_Line> t_Line2 { get; set; }
        public virtual t_Tracker t_Tracker { get; set; }
    }
}
