//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationRaceLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Map
    {
        public t_Map()
        {
            this.t_Parcour = new HashSet<t_Parcour>();
        }
    
        public int ID { get; set; }
        public int ID_Picture { get; set; }
        public string Name { get; set; }
        public double XSize { get; set; }
        public double YSize { get; set; }
        public double XRot { get; set; }
        public double YRot { get; set; }
        public double XTopLeft { get; set; }
        public double YTopLeft { get; set; }
        public int ID_CompetitionSet { get; set; }
    
        public virtual t_CompetitionSet t_CompetitionSet { get; set; }
        public virtual ICollection<t_Parcour> t_Parcour { get; set; }
        public virtual t_Picture t_Picture { get; set; }
    }
}
