//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationRaceLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Parcour
    {
        public t_Parcour()
        {
            this.t_Line = new HashSet<t_Line>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ID_Map { get; set; }
        public int ID_CompetitionSet { get; set; }
    
        public virtual t_Map t_Map { get; set; }
        public virtual t_CompetitionSet t_CompetitionSet { get; set; }
        public virtual ICollection<t_Line> t_Line { get; set; }
    }
}
