//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GELive.ANRLDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="t_Daten", Namespace="http://schemas.datacontract.org/2004/07/DataService")]
    [System.SerializableAttribute()]
    public partial class t_Daten : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AltitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PolygonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PenaltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((this.AltitudeField.Equals(value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Polygon {
            get {
                return this.ID_PolygonField;
            }
            set {
                if ((this.ID_PolygonField.Equals(value) != true)) {
                    this.ID_PolygonField = value;
                    this.RaisePropertyChanged("ID_Polygon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Tracker {
            get {
                return this.ID_TrackerField;
            }
            set {
                if ((this.ID_TrackerField.Equals(value) != true)) {
                    this.ID_TrackerField = value;
                    this.RaisePropertyChanged("ID_Tracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Penalty {
            get {
                return this.PenaltyField;
            }
            set {
                if ((this.PenaltyField.Equals(value) != true)) {
                    this.PenaltyField = value;
                    this.RaisePropertyChanged("Penalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((this.SpeedField.Equals(value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="t_PolygonPoint", Namespace="http://schemas.datacontract.org/2004/07/DataService")]
    [System.SerializableAttribute()]
    public partial class t_PolygonPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PolygonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal altitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal longitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Polygon {
            get {
                return this.ID_PolygonField;
            }
            set {
                if ((this.ID_PolygonField.Equals(value) != true)) {
                    this.ID_PolygonField = value;
                    this.RaisePropertyChanged("ID_Polygon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal altitude {
            get {
                return this.altitudeField;
            }
            set {
                if ((this.altitudeField.Equals(value) != true)) {
                    this.altitudeField = value;
                    this.RaisePropertyChanged("altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ANRLDataService.IANRLDataService")]
    public interface IANRLDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/GetPathData", ReplyAction="http://tempuri.org/IANRLDataService/GetPathDataResponse")]
        System.Collections.Generic.List<GELive.ANRLDataService.t_Daten> GetPathData(System.DateTime timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/GetTimestamps", ReplyAction="http://tempuri.org/IANRLDataService/GetTimestampsResponse")]
        System.Collections.Generic.List<System.DateTime> GetTimestamps();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/GetPolygons", ReplyAction="http://tempuri.org/IANRLDataService/GetPolygonsResponse")]
        System.Collections.Generic.List<GELive.ANRLDataService.t_PolygonPoint> GetPolygons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/GetTrackers", ReplyAction="http://tempuri.org/IANRLDataService/GetTrackersResponse")]
        System.Collections.Generic.List<System.Collections.Generic.List<string>> GetTrackers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/GetPilots", ReplyAction="http://tempuri.org/IANRLDataService/GetPilotsResponse")]
        System.Collections.Generic.List<System.Collections.Generic.List<string>> GetPilots();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/GetRaces", ReplyAction="http://tempuri.org/IANRLDataService/GetRacesResponse")]
        System.Collections.Generic.List<System.Collections.Generic.List<string>> GetRaces();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/RemoveRace", ReplyAction="http://tempuri.org/IANRLDataService/RemoveRaceResponse")]
        void RemoveRace(int Race_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/CleanTracker", ReplyAction="http://tempuri.org/IANRLDataService/CleanTrackerResponse")]
        void CleanTracker(int TrackerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/AddNewPilot", ReplyAction="http://tempuri.org/IANRLDataService/AddNewPilotResponse")]
        void AddNewPilot(int TrackerID, string LastName, string SureName, string Color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/AddPilot", ReplyAction="http://tempuri.org/IANRLDataService/AddPilotResponse")]
        void AddPilot(int PilotID, int TrackerID, string LastName, string SureName, string Color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/AddPolygons", ReplyAction="http://tempuri.org/IANRLDataService/AddPolygonsResponse")]
        void AddPolygons(System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.List<double>>> PolygonList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IANRLDataServiceChannel : GELive.ANRLDataService.IANRLDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ANRLDataServiceClient : System.ServiceModel.ClientBase<GELive.ANRLDataService.IANRLDataService>, GELive.ANRLDataService.IANRLDataService {
        
        public ANRLDataServiceClient() {
        }
        
        public ANRLDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ANRLDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ANRLDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ANRLDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<GELive.ANRLDataService.t_Daten> GetPathData(System.DateTime timestamp) {
            return base.Channel.GetPathData(timestamp);
        }
        
        public System.Collections.Generic.List<System.DateTime> GetTimestamps() {
            return base.Channel.GetTimestamps();
        }
        
        public System.Collections.Generic.List<GELive.ANRLDataService.t_PolygonPoint> GetPolygons() {
            return base.Channel.GetPolygons();
        }
        
        public System.Collections.Generic.List<System.Collections.Generic.List<string>> GetTrackers() {
            return base.Channel.GetTrackers();
        }
        
        public System.Collections.Generic.List<System.Collections.Generic.List<string>> GetPilots() {
            return base.Channel.GetPilots();
        }
        
        public System.Collections.Generic.List<System.Collections.Generic.List<string>> GetRaces() {
            return base.Channel.GetRaces();
        }
        
        public void RemoveRace(int Race_ID) {
            base.Channel.RemoveRace(Race_ID);
        }
        
        public void CleanTracker(int TrackerID) {
            base.Channel.CleanTracker(TrackerID);
        }
        
        public void AddNewPilot(int TrackerID, string LastName, string SureName, string Color) {
            base.Channel.AddNewPilot(TrackerID, LastName, SureName, Color);
        }
        
        public void AddPilot(int PilotID, int TrackerID, string LastName, string SureName, string Color) {
            base.Channel.AddPilot(PilotID, TrackerID, LastName, SureName, Color);
        }
        
        public void AddPolygons(System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.List<double>>> PolygonList) {
            base.Channel.AddPolygons(PolygonList);
        }
    }
}
