//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GELive.anrlWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="t_Daten", Namespace="http://schemas.datacontract.org/2004/07/DataService")]
    [System.SerializableAttribute()]
    public partial class t_Daten : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_FlugzeugField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_PolygonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PenaltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> XEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> XStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> YEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> YStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ZEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ZStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GELive.anrlWebService.t_Flugzeug t_FlugzeugField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Flugzeug {
            get {
                return this.ID_FlugzeugField;
            }
            set {
                if ((this.ID_FlugzeugField.Equals(value) != true)) {
                    this.ID_FlugzeugField = value;
                    this.RaisePropertyChanged("ID_Flugzeug");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_Polygon {
            get {
                return this.ID_PolygonField;
            }
            set {
                if ((this.ID_PolygonField.Equals(value) != true)) {
                    this.ID_PolygonField = value;
                    this.RaisePropertyChanged("ID_Polygon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Penalty {
            get {
                return this.PenaltyField;
            }
            set {
                if ((this.PenaltyField.Equals(value) != true)) {
                    this.PenaltyField = value;
                    this.RaisePropertyChanged("Penalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((object.ReferenceEquals(this.SpeedField, value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TEnd {
            get {
                return this.TEndField;
            }
            set {
                if ((this.TEndField.Equals(value) != true)) {
                    this.TEndField = value;
                    this.RaisePropertyChanged("TEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TStart {
            get {
                return this.TStartField;
            }
            set {
                if ((this.TStartField.Equals(value) != true)) {
                    this.TStartField = value;
                    this.RaisePropertyChanged("TStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> XEnd {
            get {
                return this.XEndField;
            }
            set {
                if ((this.XEndField.Equals(value) != true)) {
                    this.XEndField = value;
                    this.RaisePropertyChanged("XEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> XStart {
            get {
                return this.XStartField;
            }
            set {
                if ((this.XStartField.Equals(value) != true)) {
                    this.XStartField = value;
                    this.RaisePropertyChanged("XStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> YEnd {
            get {
                return this.YEndField;
            }
            set {
                if ((this.YEndField.Equals(value) != true)) {
                    this.YEndField = value;
                    this.RaisePropertyChanged("YEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> YStart {
            get {
                return this.YStartField;
            }
            set {
                if ((this.YStartField.Equals(value) != true)) {
                    this.YStartField = value;
                    this.RaisePropertyChanged("YStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ZEnd {
            get {
                return this.ZEndField;
            }
            set {
                if ((this.ZEndField.Equals(value) != true)) {
                    this.ZEndField = value;
                    this.RaisePropertyChanged("ZEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ZStart {
            get {
                return this.ZStartField;
            }
            set {
                if ((this.ZStartField.Equals(value) != true)) {
                    this.ZStartField = value;
                    this.RaisePropertyChanged("ZStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GELive.anrlWebService.t_Flugzeug t_Flugzeug {
            get {
                return this.t_FlugzeugField;
            }
            set {
                if ((object.ReferenceEquals(this.t_FlugzeugField, value) != true)) {
                    this.t_FlugzeugField = value;
                    this.RaisePropertyChanged("t_Flugzeug");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="t_Flugzeug", Namespace="http://schemas.datacontract.org/2004/07/DataService")]
    [System.SerializableAttribute()]
    public partial class t_Flugzeug : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlugzeugField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_GPS_TrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PilotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GELive.anrlWebService.t_Daten[] t_DatensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GELive.anrlWebService.t_Tracker t_TrackerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flugzeug {
            get {
                return this.FlugzeugField;
            }
            set {
                if ((object.ReferenceEquals(this.FlugzeugField, value) != true)) {
                    this.FlugzeugField = value;
                    this.RaisePropertyChanged("Flugzeug");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_GPS_Tracker {
            get {
                return this.ID_GPS_TrackerField;
            }
            set {
                if ((this.ID_GPS_TrackerField.Equals(value) != true)) {
                    this.ID_GPS_TrackerField = value;
                    this.RaisePropertyChanged("ID_GPS_Tracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pilot {
            get {
                return this.PilotField;
            }
            set {
                if ((object.ReferenceEquals(this.PilotField, value) != true)) {
                    this.PilotField = value;
                    this.RaisePropertyChanged("Pilot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GELive.anrlWebService.t_Daten[] t_Datens {
            get {
                return this.t_DatensField;
            }
            set {
                if ((object.ReferenceEquals(this.t_DatensField, value) != true)) {
                    this.t_DatensField = value;
                    this.RaisePropertyChanged("t_Datens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GELive.anrlWebService.t_Tracker t_Tracker {
            get {
                return this.t_TrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.t_TrackerField, value) != true)) {
                    this.t_TrackerField = value;
                    this.RaisePropertyChanged("t_Tracker");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="t_Tracker", Namespace="http://schemas.datacontract.org/2004/07/DataService")]
    [System.SerializableAttribute()]
    public partial class t_Tracker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMEIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GELive.anrlWebService.t_Flugzeug[] t_FlugzeugsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GELive.anrlWebService.t_GPS_IN t_GPS_INField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMEI {
            get {
                return this.IMEIField;
            }
            set {
                if ((object.ReferenceEquals(this.IMEIField, value) != true)) {
                    this.IMEIField = value;
                    this.RaisePropertyChanged("IMEI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GELive.anrlWebService.t_Flugzeug[] t_Flugzeugs {
            get {
                return this.t_FlugzeugsField;
            }
            set {
                if ((object.ReferenceEquals(this.t_FlugzeugsField, value) != true)) {
                    this.t_FlugzeugsField = value;
                    this.RaisePropertyChanged("t_Flugzeugs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GELive.anrlWebService.t_GPS_IN t_GPS_IN {
            get {
                return this.t_GPS_INField;
            }
            set {
                if ((object.ReferenceEquals(this.t_GPS_INField, value) != true)) {
                    this.t_GPS_INField = value;
                    this.RaisePropertyChanged("t_GPS_IN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="t_GPS_IN", Namespace="http://schemas.datacontract.org/2004/07/DataService")]
    [System.SerializableAttribute()]
    public partial class t_GPS_IN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GPS_fixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HDOPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMEIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ProcessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string altitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string headingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string longitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nr_used_satField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string speedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GELive.anrlWebService.t_Tracker[] t_TrackersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GPS_fix {
            get {
                return this.GPS_fixField;
            }
            set {
                if ((this.GPS_fixField.Equals(value) != true)) {
                    this.GPS_fixField = value;
                    this.RaisePropertyChanged("GPS_fix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HDOP {
            get {
                return this.HDOPField;
            }
            set {
                if ((object.ReferenceEquals(this.HDOPField, value) != true)) {
                    this.HDOPField = value;
                    this.RaisePropertyChanged("HDOP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMEI {
            get {
                return this.IMEIField;
            }
            set {
                if ((object.ReferenceEquals(this.IMEIField, value) != true)) {
                    this.IMEIField = value;
                    this.RaisePropertyChanged("IMEI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Processed {
            get {
                return this.ProcessedField;
            }
            set {
                if ((this.ProcessedField.Equals(value) != true)) {
                    this.ProcessedField = value;
                    this.RaisePropertyChanged("Processed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimestampTracker {
            get {
                return this.TimestampTrackerField;
            }
            set {
                if ((this.TimestampTrackerField.Equals(value) != true)) {
                    this.TimestampTrackerField = value;
                    this.RaisePropertyChanged("TimestampTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string altitude {
            get {
                return this.altitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.altitudeField, value) != true)) {
                    this.altitudeField = value;
                    this.RaisePropertyChanged("altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string heading {
            get {
                return this.headingField;
            }
            set {
                if ((object.ReferenceEquals(this.headingField, value) != true)) {
                    this.headingField = value;
                    this.RaisePropertyChanged("heading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.latitudeField, value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.longitudeField, value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nr_used_sat {
            get {
                return this.nr_used_satField;
            }
            set {
                if ((this.nr_used_satField.Equals(value) != true)) {
                    this.nr_used_satField = value;
                    this.RaisePropertyChanged("nr_used_sat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string speed {
            get {
                return this.speedField;
            }
            set {
                if ((object.ReferenceEquals(this.speedField, value) != true)) {
                    this.speedField = value;
                    this.RaisePropertyChanged("speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GELive.anrlWebService.t_Tracker[] t_Trackers {
            get {
                return this.t_TrackersField;
            }
            set {
                if ((object.ReferenceEquals(this.t_TrackersField, value) != true)) {
                    this.t_TrackersField = value;
                    this.RaisePropertyChanged("t_Trackers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="anrlWebService.IANRLDataService")]
    public interface IANRLDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IANRLDataService/GetPathData", ReplyAction="http://tempuri.org/IANRLDataService/GetPathDataResponse")]
        GELive.anrlWebService.t_Daten[] GetPathData(System.DateTime timestamp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IANRLDataServiceChannel : GELive.anrlWebService.IANRLDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ANRLDataServiceClient : System.ServiceModel.ClientBase<GELive.anrlWebService.IANRLDataService>, GELive.anrlWebService.IANRLDataService {
        
        public ANRLDataServiceClient() {
        }
        
        public ANRLDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ANRLDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ANRLDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ANRLDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GELive.anrlWebService.t_Daten[] GetPathData(System.DateTime timestamp) {
            return base.Channel.GetPathData(timestamp);
        }
    }
}
