ALTER TABLE [dbo].[t_Team_Tracker]
    ADD CONSTRAINT [PK_dbo.t_Team_Tracker] PRIMARY KEY CLUSTERED ([ID_Competition_Team] ASC, [ID_Tracker] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

