ALTER TABLE [dbo].[t_Parcour_Line]
    ADD CONSTRAINT [PK_dbo.t_Parcour_Line] PRIMARY KEY CLUSTERED ([ID_Parcour] ASC, [ID_Line] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

