//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: anrl.proto
namespace NetworkObjects
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Root")]
  public partial class Root : global::ProtoBuf.IExtensible
  {
    public Root() {}
    

    private NetworkObjects.AuthenticationInfo _AuthInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AuthInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.AuthenticationInfo AuthInfo
    {
      get { return _AuthInfo; }
      set { _AuthInfo = value; }
    }

    private int _RequestType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RequestType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RequestType
    {
      get { return _RequestType; }
      set { _RequestType = value; }
    }

    private int _ObjectType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ObjectType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ObjectType
    {
      get { return _ObjectType; }
      set { _ObjectType = value; }
    }

    private NetworkObjects.RequestParameters _RequestParameters = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"RequestParameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.RequestParameters RequestParameters
    {
      get { return _RequestParameters; }
      set { _RequestParameters = value; }
    }

    private NetworkObjects.ResponseParameters _ResponseParameters = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ResponseParameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.ResponseParameters ResponseParameters
    {
      get { return _ResponseParameters; }
      set { _ResponseParameters = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthenticationInfo")]
  public partial class AuthenticationInfo : global::ProtoBuf.IExtensible
  {
    public AuthenticationInfo() {}
    

    private string _Username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Username
    {
      get { return _Username; }
      set { _Username = value; }
    }

    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }

    private string _Token = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Token
    {
      get { return _Token; }
      set { _Token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestParameters")]
  public partial class RequestParameters : global::ProtoBuf.IExtensible
  {
    public RequestParameters() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _IDS = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"IDS", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> IDS
    {
      get { return _IDS; }
    }
  

    private NetworkObjects.Picture _Picture = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Picture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.Picture Picture
    {
      get { return _Picture; }
      set { _Picture = value; }
    }

    private NetworkObjects.Map _Map = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.Map Map
    {
      get { return _Map; }
      set { _Map = value; }
    }

    private NetworkObjects.Parcour _Parcour = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Parcour", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.Parcour Parcour
    {
      get { return _Parcour; }
      set { _Parcour = value; }
    }

    private NetworkObjects.Tracker _Tracker = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Tracker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.Tracker Tracker
    {
      get { return _Tracker; }
      set { _Tracker = value; }
    }

    private NetworkObjects.Pilot _Pilot = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Pilot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.Pilot Pilot
    {
      get { return _Pilot; }
      set { _Pilot = value; }
    }

    private NetworkObjects.Team _Team = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Team", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.Team Team
    {
      get { return _Team; }
      set { _Team = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseParameters")]
  public partial class ResponseParameters : global::ProtoBuf.IExtensible
  {
    public ResponseParameters() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _DeletedIDList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"DeletedIDList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> DeletedIDList
    {
      get { return _DeletedIDList; }
    }
  

    private string _Exception = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Exception", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Exception
    {
      get { return _Exception; }
      set { _Exception = value; }
    }
    private readonly global::System.Collections.Generic.List<NetworkObjects.Picture> _PictureList = new global::System.Collections.Generic.List<NetworkObjects.Picture>();
    [global::ProtoBuf.ProtoMember(4, Name=@"PictureList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NetworkObjects.Picture> PictureList
    {
      get { return _PictureList; }
    }
  
    private readonly global::System.Collections.Generic.List<NetworkObjects.Map> _MapList = new global::System.Collections.Generic.List<NetworkObjects.Map>();
    [global::ProtoBuf.ProtoMember(5, Name=@"MapList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NetworkObjects.Map> MapList
    {
      get { return _MapList; }
    }
  
    private readonly global::System.Collections.Generic.List<NetworkObjects.Parcour> _ParcourList = new global::System.Collections.Generic.List<NetworkObjects.Parcour>();
    [global::ProtoBuf.ProtoMember(6, Name=@"ParcourList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NetworkObjects.Parcour> ParcourList
    {
      get { return _ParcourList; }
    }
  
    private readonly global::System.Collections.Generic.List<NetworkObjects.Tracker> _TrackerList = new global::System.Collections.Generic.List<NetworkObjects.Tracker>();
    [global::ProtoBuf.ProtoMember(7, Name=@"TrackerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NetworkObjects.Tracker> TrackerList
    {
      get { return _TrackerList; }
    }
  
    private readonly global::System.Collections.Generic.List<NetworkObjects.Pilot> _PilotList = new global::System.Collections.Generic.List<NetworkObjects.Pilot>();
    [global::ProtoBuf.ProtoMember(8, Name=@"PilotList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NetworkObjects.Pilot> PilotList
    {
      get { return _PilotList; }
    }
  
    private readonly global::System.Collections.Generic.List<NetworkObjects.Team> _TeamList = new global::System.Collections.Generic.List<NetworkObjects.Team>();
    [global::ProtoBuf.ProtoMember(9, Name=@"TeamList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NetworkObjects.Team> TeamList
    {
      get { return _TeamList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Picture")]
  public partial class Picture : global::ProtoBuf.IExtensible
  {
    public Picture() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }

    private byte[] _Image = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] Image
    {
      get { return _Image; }
      set { _Image = value; }
    }

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Map")]
  public partial class Map : global::ProtoBuf.IExtensible
  {
    public Map() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }

    private int _ID_Picture = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ID_Picture", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID_Picture
    {
      get { return _ID_Picture; }
      set { _ID_Picture = value; }
    }

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private double _XSize = default(double);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"XSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double XSize
    {
      get { return _XSize; }
      set { _XSize = value; }
    }

    private double _YSize = default(double);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"YSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double YSize
    {
      get { return _YSize; }
      set { _YSize = value; }
    }

    private double _XRot = default(double);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"XRot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double XRot
    {
      get { return _XRot; }
      set { _XRot = value; }
    }

    private double _YRot = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"YRot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double YRot
    {
      get { return _YRot; }
      set { _YRot = value; }
    }

    private double _XTopLeft = default(double);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"XTopLeft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double XTopLeft
    {
      get { return _XTopLeft; }
      set { _XTopLeft = value; }
    }

    private double _YTopLeft = default(double);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"YTopLeft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double YTopLeft
    {
      get { return _YTopLeft; }
      set { _YTopLeft = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Parcour")]
  public partial class Parcour : global::ProtoBuf.IExtensible
  {
    public Parcour() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private readonly global::System.Collections.Generic.List<NetworkObjects.Line> _LineList = new global::System.Collections.Generic.List<NetworkObjects.Line>();
    [global::ProtoBuf.ProtoMember(2, Name=@"LineList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NetworkObjects.Line> LineList
    {
      get { return _LineList; }
    }
  

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private int _ID_Map = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ID_Map", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID_Map
    {
      get { return _ID_Map; }
      set { _ID_Map = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Line")]
  public partial class Line : global::ProtoBuf.IExtensible
  {
    public Line() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }

    private NetworkObjects.Point _A = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"A", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.Point A
    {
      get { return _A; }
      set { _A = value; }
    }

    private NetworkObjects.Point _B = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"B", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.Point B
    {
      get { return _B; }
      set { _B = value; }
    }

    private NetworkObjects.Point _O = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"O", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.Point O
    {
      get { return _O; }
      set { _O = value; }
    }

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Point")]
  public partial class Point : global::ProtoBuf.IExtensible
  {
    public Point() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }

    private double _altitude = default(double);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"altitude", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double altitude
    {
      get { return _altitude; }
      set { _altitude = value; }
    }

    private double _longitude = default(double);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"longitude", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double longitude
    {
      get { return _longitude; }
      set { _longitude = value; }
    }

    private double _latitude = default(double);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"latitude", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double latitude
    {
      get { return _latitude; }
      set { _latitude = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tracker")]
  public partial class Tracker : global::ProtoBuf.IExtensible
  {
    public Tracker() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }

    private string _IMEI = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IMEI", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IMEI
    {
      get { return _IMEI; }
      set { _IMEI = value; }
    }

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Pilot")]
  public partial class Pilot : global::ProtoBuf.IExtensible
  {
    public Pilot() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private string _Surename = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Surename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Surename
    {
      get { return _Surename; }
      set { _Surename = value; }
    }

    private int _ID_Picture = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ID_Picture", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID_Picture
    {
      get { return _ID_Picture; }
      set { _ID_Picture = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Team")]
  public partial class Team : global::ProtoBuf.IExtensible
  {
    public Team() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }

    private int _ID_Pilot = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ID_Pilot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID_Pilot
    {
      get { return _ID_Pilot; }
      set { _ID_Pilot = value; }
    }

    private int _ID_Navigator = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ID_Navigator", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID_Navigator
    {
      get { return _ID_Navigator; }
      set { _ID_Navigator = value; }
    }

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private string _Color = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Color", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Color
    {
      get { return _Color; }
      set { _Color = value; }
    }

    private int _ID_Flag = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ID_Flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID_Flag
    {
      get { return _ID_Flag; }
      set { _ID_Flag = value; }
    }

    private string _Description = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Description
    {
      get { return _Description; }
      set { _Description = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _ID_Tracker = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"ID_Tracker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> ID_Tracker
    {
      get { return _ID_Tracker; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RootMessage")]
  public partial class RootMessage : global::ProtoBuf.IExtensible
  {
    public RootMessage() {}
    
    private readonly global::System.Collections.Generic.List<NetworkObjects.GPSData> _gpsdata = new global::System.Collections.Generic.List<NetworkObjects.GPSData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gpsdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NetworkObjects.GPSData> gpsdata
    {
      get { return _gpsdata; }
    }
  

    private NetworkObjects.Response _response = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NetworkObjects.Response response
    {
      get { return _response; }
      set { _response = value; }
    }

    private string _exception = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"exception", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string exception
    {
      get { return _exception; }
      set { _exception = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GPSData")]
  public partial class GPSData : global::ProtoBuf.IExtensible
  {
    public GPSData() {}
    

    private long _timestampSender = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"timestampSender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestampSender
    {
      get { return _timestampSender; }
      set { _timestampSender = value; }
    }

    private long _timestampGPS = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"timestampGPS", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestampGPS
    {
      get { return _timestampGPS; }
      set { _timestampGPS = value; }
    }

    private double _altitude = default(double);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"altitude", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double altitude
    {
      get { return _altitude; }
      set { _altitude = value; }
    }

    private double _latitude = default(double);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"latitude", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double latitude
    {
      get { return _latitude; }
      set { _latitude = value; }
    }

    private double _longitude = default(double);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"longitude", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double longitude
    {
      get { return _longitude; }
      set { _longitude = value; }
    }

    private double _accuracy = default(double);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"accuracy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double accuracy
    {
      get { return _accuracy; }
      set { _accuracy = value; }
    }

    private double _speed = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double speed
    {
      get { return _speed; }
      set { _speed = value; }
    }

    private double _bearing = default(double);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"bearing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double bearing
    {
      get { return _bearing; }
      set { _bearing = value; }
    }

    private string _identifier = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"identifier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string identifier
    {
      get { return _identifier; }
      set { _identifier = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    

    private int _countAdded = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"countAdded", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int countAdded
    {
      get { return _countAdded; }
      set { _countAdded = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
