CREATE TABLE [dbo].[t_PenaltyZonePolygon](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_PolygonGroup] [int] NOT NULL,
	[Type] [int] NOT NULL,
 CONSTRAINT [PK_t_Polygon_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


