CREATE TABLE [dbo].[t_Pilot](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LastName] [text] NOT NULL,
	[SureName] [text] NULL,
	[ID_Picture] [int] NULL,
 CONSTRAINT [PK_t_Pilot] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


