CREATE TABLE [dbo].[t_Picture](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Data] [image] NOT NULL,
	[Name] [nchar](50) NOT NULL,
	[isFlag] [bit] NOT NULL,
 CONSTRAINT [PK_t_Picture] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


