CREATE TABLE [dbo].[t_Race_Team](
	[ID] [int] NOT NULL,
	[ID_Race] [int] NOT NULL,
	[ID_Team] [int] NOT NULL,
 CONSTRAINT [PK_t_Race_Team] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


