CREATE TABLE [dbo].[t_Tracker](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IMEI] [nchar](20) NOT NULL,
	[Name] [nchar](20) NULL,
 CONSTRAINT [PK_t_Tracker] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


