<?xml version="1.0" encoding="utf-8"?><Database Name="AnrlDB" Class="AnrlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=AnrlDB;Integrated Security=True" SettingsObjectName="AnrlDB.Properties.Settings" SettingsPropertyName="AnrlDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.t_Competition" Member="t_Competitions">
    <Type Name="t_Competition">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TimeTakeOff" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TimeStartLine" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TimeEndLine" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ID_TakeOffLine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Parcour" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_CompetitionSet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_Competition_t_Competition_Team" Member="t_Competition_Teams" ThisKey="ID" OtherKey="ID_Competition" Type="t_Competition_Team" />
      <Association Name="t_CompetitionSet_t_Competition" Member="t_CompetitionSet" ThisKey="ID_CompetitionSet" OtherKey="ID" Type="t_CompetitionSet" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="t_Line_t_Competition" Member="t_Line" ThisKey="ID_TakeOffLine" OtherKey="ID" Type="t_Line" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_User_Sessions" Member="t_User_Sessions">
    <Type Name="t_User_Session">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ValidUntil" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="Identification" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrivateKey" Type="System.Data.Linq.Binary" DbType="Binary(1024) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PublicKey" Type="System.Data.Linq.Binary" DbType="Binary(1024) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SymKey" Type="System.Data.Linq.Binary" DbType="Binary(4096) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="t_User_t_User_Session" Member="t_User" ThisKey="ID_User" OtherKey="ID" Type="t_User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Competition_Team" Member="t_Competition_Teams">
    <Type Name="t_Competition_Team">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Route" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Team" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Competition" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeTakeOff" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TimeStart" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TimeEnd" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ID_CompetitionSet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_Competition_Team_t_Penalty" Member="t_Penalties" ThisKey="ID" OtherKey="ID_Competition_Team" Type="t_Penalty" />
      <Association Name="t_Competition_Team_t_Team_Tracker" Member="t_Team_Trackers" ThisKey="ID" OtherKey="ID_Competition_Team" Type="t_Team_Tracker" />
      <Association Name="t_Competition_t_Competition_Team" Member="t_Competition" ThisKey="ID_Competition" OtherKey="ID" Type="t_Competition" IsForeignKey="true" />
      <Association Name="t_CompetitionSet_t_Competition_Team" Member="t_CompetitionSet" ThisKey="ID_CompetitionSet" OtherKey="ID" Type="t_CompetitionSet" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="t_Team_t_Competition_Team" Member="t_Team" ThisKey="ID_Team" OtherKey="ID" Type="t_Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_CompetitionSet" Member="t_CompetitionSets">
    <Type Name="t_CompetitionSet">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Owner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PublicRole" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_CompetitionSet_t_Competition" Member="t_Competitions" ThisKey="ID" OtherKey="ID_CompetitionSet" Type="t_Competition" />
      <Association Name="t_CompetitionSet_t_Competition_Team" Member="t_Competition_Teams" ThisKey="ID" OtherKey="ID_CompetitionSet" Type="t_Competition_Team" />
      <Association Name="t_CompetitionSet_t_Map" Member="t_Maps" ThisKey="ID" OtherKey="ID_CompetitionSet" Type="t_Map" />
      <Association Name="t_CompetitionSet_t_Parcour" Member="t_Parcours" ThisKey="ID" OtherKey="ID_CompetitionSet" Type="t_Parcour" />
      <Association Name="t_CompetitionSet_t_Penalty" Member="t_Penalties" ThisKey="ID" OtherKey="ID_CompetitionSet" Type="t_Penalty" />
      <Association Name="t_CompetitionSet_t_Picture" Member="t_Pictures" ThisKey="ID" OtherKey="ID_CompetitionSet" Type="t_Picture" />
      <Association Name="t_CompetitionSet_t_Pilot" Member="t_Pilots" ThisKey="ID" OtherKey="ID_CompetitionSet" Type="t_Pilot" />
      <Association Name="t_CompetitionSet_t_Team" Member="t_Teams" ThisKey="ID" OtherKey="ID_CompetitionSet" Type="t_Team" />
      <Association Name="t_CompetitionSet_t_User_CompetitionSet" Member="t_User_CompetitionSets" ThisKey="ID" OtherKey="ID_CompetitionSet" Type="t_User_CompetitionSet" />
      <Association Name="t_User_t_CompetitionSet" Member="t_User" ThisKey="ID_Owner" OtherKey="ID" Type="t_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Daten" Member="t_Datens">
    <Type Name="t_Daten">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Tracker" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Altitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Speed" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Accuracy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Bearing" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="t_Tracker_t_Daten" Member="t_Tracker" ThisKey="ID_Tracker" OtherKey="ID" Type="t_Tracker" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_GPS_IN" Member="t_GPS_INs">
    <Type Name="t_GPS_IN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IMEI" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GPS_fix" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimestampTracker" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="longitude" Type="System.String" DbType="NChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.String" DbType="NChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="altitude" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="speed" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="heading" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="nr_used_sat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HDOP" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Processed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.t_GPSPoint" Member="t_GPSPoints">
    <Type Name="t_GPSPoint">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="altitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="t_GPSPoint_t_Line" Member="t_Lines" ThisKey="ID" OtherKey="ID_PointA" Type="t_Line" />
      <Association Name="t_GPSPoint_t_Line1" Member="t_Lines1" ThisKey="ID" OtherKey="ID_PointB" Type="t_Line" />
      <Association Name="t_GPSPoint_t_Line2" Member="t_Lines2" ThisKey="ID" OtherKey="ID_PointOrientation" Type="t_Line" />
    </Type>
  </Table>
  <Table Name="dbo.t_Line" Member="t_Lines">
    <Type Name="t_Line">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_PointA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_PointB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_PointOrientation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_Line_t_Competition" Member="t_Competitions" ThisKey="ID" OtherKey="ID_TakeOffLine" Type="t_Competition" />
      <Association Name="t_Line_t_Parcour_Line" Member="t_Parcour_Lines" ThisKey="ID" OtherKey="ID_Line" Type="t_Parcour_Line" />
      <Association Name="t_GPSPoint_t_Line" Member="t_GPSPoint" ThisKey="ID_PointA" OtherKey="ID" Type="t_GPSPoint" IsForeignKey="true" />
      <Association Name="t_GPSPoint_t_Line1" Member="t_GPSPoint1" ThisKey="ID_PointB" OtherKey="ID" Type="t_GPSPoint" IsForeignKey="true" />
      <Association Name="t_GPSPoint_t_Line2" Member="t_GPSPoint2" ThisKey="ID_PointOrientation" OtherKey="ID" Type="t_GPSPoint" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Log" Member="t_Logs">
    <Type Name="t_Log">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="project" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.t_Map" Member="t_Maps">
    <Type Name="t_Map">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Picture" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="XSize" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="YSize" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="XRot" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="YRot" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="XTopLeft" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="YTopLeft" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ID_CompetitionSet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_Map_t_Parcour" Member="t_Parcours" ThisKey="ID" OtherKey="ID_Map" Type="t_Parcour" />
      <Association Name="t_CompetitionSet_t_Map" Member="t_CompetitionSet" ThisKey="ID_CompetitionSet" OtherKey="ID" Type="t_CompetitionSet" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="t_Picture_t_Map" Member="t_Picture" ThisKey="ID_Picture" OtherKey="ID" Type="t_Picture" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Parcour" Member="t_Parcours">
    <Type Name="t_Parcour">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Map" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_CompetitionSet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_Parcour_t_Parcour_Line" Member="t_Parcour_Lines" ThisKey="ID" OtherKey="ID_Parcour" Type="t_Parcour_Line" />
      <Association Name="t_CompetitionSet_t_Parcour" Member="t_CompetitionSet" ThisKey="ID_CompetitionSet" OtherKey="ID" Type="t_CompetitionSet" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="t_Map_t_Parcour" Member="t_Map" ThisKey="ID_Map" OtherKey="ID" Type="t_Map" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Parcour_Line" Member="t_Parcour_Lines">
    <Type Name="t_Parcour_Line">
      <Column Name="ID_Parcour" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Line" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="t_Line_t_Parcour_Line" Member="t_Line" ThisKey="ID_Line" OtherKey="ID" Type="t_Line" IsForeignKey="true" />
      <Association Name="t_Parcour_t_Parcour_Line" Member="t_Parcour" ThisKey="ID_Parcour" OtherKey="ID" Type="t_Parcour" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Penalty" Member="t_Penalties">
    <Type Name="t_Penalty">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Competition_Team" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_CompetitionSet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_Competition_Team_t_Penalty" Member="t_Competition_Team" ThisKey="ID_Competition_Team" OtherKey="ID" Type="t_Competition_Team" IsForeignKey="true" />
      <Association Name="t_CompetitionSet_t_Penalty" Member="t_CompetitionSet" ThisKey="ID_CompetitionSet" OtherKey="ID" Type="t_CompetitionSet" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Picture" Member="t_Pictures">
    <Type Name="t_Picture">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="isFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ID_CompetitionSet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_Picture_t_Map" Member="t_Maps" ThisKey="ID" OtherKey="ID_Picture" Type="t_Map" />
      <Association Name="t_Picture_t_Pilot" Member="t_Pilots" ThisKey="ID" OtherKey="ID_Picture" Type="t_Pilot" />
      <Association Name="t_Picture_t_Team" Member="t_Teams" ThisKey="ID" OtherKey="ID_Flag" Type="t_Team" />
      <Association Name="t_CompetitionSet_t_Picture" Member="t_CompetitionSet" ThisKey="ID_CompetitionSet" OtherKey="ID" Type="t_CompetitionSet" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Pilot" Member="t_Pilots">
    <Type Name="t_Pilot">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SureName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Picture" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_CompetitionSet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_Pilot_t_Team" Member="t_Teams" ThisKey="ID" OtherKey="ID_Pilot" Type="t_Team" />
      <Association Name="t_Pilot_t_Team1" Member="t_Teams1" ThisKey="ID" OtherKey="ID_Navigator" Type="t_Team" />
      <Association Name="t_CompetitionSet_t_Pilot" Member="t_CompetitionSet" ThisKey="ID_CompetitionSet" OtherKey="ID" Type="t_CompetitionSet" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="t_Picture_t_Pilot" Member="t_Picture" ThisKey="ID_Picture" OtherKey="ID" Type="t_Picture" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Team" Member="t_Teams">
    <Type Name="t_Team">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_Pilot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Navigator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ID_Flag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ID_CompetitionSet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="t_Team_t_Competition_Team" Member="t_Competition_Teams" ThisKey="ID" OtherKey="ID_Team" Type="t_Competition_Team" />
      <Association Name="t_CompetitionSet_t_Team" Member="t_CompetitionSet" ThisKey="ID_CompetitionSet" OtherKey="ID" Type="t_CompetitionSet" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="t_Picture_t_Team" Member="t_Picture" ThisKey="ID_Flag" OtherKey="ID" Type="t_Picture" IsForeignKey="true" />
      <Association Name="t_Pilot_t_Team" Member="t_Pilot" ThisKey="ID_Pilot" OtherKey="ID" Type="t_Pilot" IsForeignKey="true" />
      <Association Name="t_Pilot_t_Team1" Member="t_Pilot1" ThisKey="ID_Navigator" OtherKey="ID" Type="t_Pilot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Team_Tracker" Member="t_Team_Trackers">
    <Type Name="t_Team_Tracker">
      <Column Name="ID_Competition_Team" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Tracker" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="t_Competition_Team_t_Team_Tracker" Member="t_Competition_Team" ThisKey="ID_Competition_Team" OtherKey="ID" Type="t_Competition_Team" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="t_Tracker_t_Team_Tracker" Member="t_Tracker" ThisKey="ID_Tracker" OtherKey="ID" Type="t_Tracker" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Tracker" Member="t_Trackers">
    <Type Name="t_Tracker">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IMEI" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="t_Tracker_t_Daten" Member="t_Datens" ThisKey="ID" OtherKey="ID_Tracker" Type="t_Daten" />
      <Association Name="t_Tracker_t_Team_Tracker" Member="t_Team_Trackers" ThisKey="ID" OtherKey="ID_Tracker" Type="t_Team_Tracker" />
    </Type>
  </Table>
  <Table Name="dbo.t_User" Member="t_Users">
    <Type Name="t_User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(265) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_User_t_User_Session" Member="t_User_Sessions" ThisKey="ID" OtherKey="ID_User" Type="t_User_Session" />
      <Association Name="t_User_t_CompetitionSet" Member="t_CompetitionSets" ThisKey="ID" OtherKey="ID_Owner" Type="t_CompetitionSet" />
      <Association Name="t_User_t_User_CompetitionSet" Member="t_User_CompetitionSets" ThisKey="ID" OtherKey="ID_User" Type="t_User_CompetitionSet" />
    </Type>
  </Table>
  <Table Name="dbo.t_User_CompetitionSet" Member="t_User_CompetitionSets">
    <Type Name="t_User_CompetitionSet">
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_CompetitionSet" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Access" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="t_CompetitionSet_t_User_CompetitionSet" Member="t_CompetitionSet" ThisKey="ID_CompetitionSet" OtherKey="ID" Type="t_CompetitionSet" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="t_User_t_User_CompetitionSet" Member="t_User" ThisKey="ID_User" OtherKey="ID" Type="t_User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>